version: "3.0"
services: 
  elasticsearch:
    image: elasticsearch:7.8.0
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  kibana:
    image: kibana:7.8.0
    container_name: kibana
    ports:
      - 5601:5601
    volumes:
      - ./conf/kibana.yml:/usr/share/kibana/config/kibana.yml
  logstash:
    image: logstash:7.8.0
    container_name: logstash
    environment:
      - ES_JAVA_OPTS="-Duser.timezone=Asia/Shanghai"
    ports:
      - 5044:5044
      - 9600:9600
    volumes:
      - ./logstash/config:/usr/share/logstash/config
      - ./logstash/data:/usr/share/logstash/data
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logs/access.log:/var/log/nginx/access.log
      - ./logstash/config/GeoLite2-City.mmdb:/usr/share/logstash/config/GeoLite2-City.mmdb
  nginx:
    image: nginx:1.12.0
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./logs/access.log:/var/log/nginx/host.access.log
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf


    